[project]
name = "fastapi-factory-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "bcrypt>=5.0.0",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "psycopg2>=2.9.12",
    "pyjwt>=2.14.0",
    "sqladmin>=0.31.1",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
