"""first_migrations

Revision ID: 291b00003eb2
Revises: 
Create Date: 2026-09-12 21:47:55.956083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291b00003eb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('grades', postgresql.ENUM('RANK_1_2', 'RANK_3_4', 'RANK_5_6', 'ENGINEER_NO_CAT', 'ENGINEER_CAT_3', 'ENGINEER_CAT_2', 'ENGINEER_CAT_1', 'CHIEF_SPECIALIST', 'FOREMAN', 'SHOP_CHIEF', 'CHIEF_ENGINEER', 'FACTORY_DIRECTOR', name='factoryrank'), nullable=False),
    sa.Column('password', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('IN_QUEUE', 'ASSEMBLING', 'TESTING', 'READY_FOR_SHIPMENT', name='boilerstatus'), nullable=False),
    sa.Column('boiler', sa.String(length=30), nullable=False),
    sa.Column('power', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('who_work', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['who_work'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('workers')
    # ### end Alembic commands ###
