"""create_new_id_worker

Revision ID: 52dd01d4aebd
Revises: 1651221cb1fc
Create Date: 2026-09-15 20:40:30.249366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dd01d4aebd'
down_revision: Union[str, Sequence[str], None] = '1651221cb1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('verification_id', sa.VARCHAR(length=8), nullable=True))
    op.create_unique_constraint(None, 'workers', ['verification_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_column('workers', 'verification_id')
    # ### end Alembic commands ###
